global:
  message: Welcome to customer service dev environment

server:
  port: 8082

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
