spring:
  application:
    name: order-service

server:
  port: 8083

global:
  message: Welcome to order service environment

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
