global:
  message: Welcome to order service prod environment

server:
  port: 8083
   message:  hello from Order Prod
   spring:
  application:
    name: order-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
